# Generated by Django 3.1 on 2020-09-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0002_auto_20200912_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Displayb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bdgd', models.ImageField(upload_to='men/images/')),
            ],
        ),
    ]
