# Generated by Django 3.1 on 2020-09-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0003_displayb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Displayb',
        ),
        migrations.AddField(
            model_name='display',
            name='bdgd',
            field=models.ImageField(blank=True, upload_to='men/images/'),
        ),
    ]
