# Generated by Django 3.1 on 2020-09-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0004_auto_20200922_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='display2',
            name='bdgd',
            field=models.ImageField(blank=True, upload_to='men/images/'),
        ),
        migrations.AlterField(
            model_name='display',
            name='desc',
            field=models.CharField(max_length=200),
        ),
    ]
