# Generated by Django 3.1 on 2020-09-23 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0005_auto_20200922_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='display3',
            name='bdgd',
            field=models.ImageField(blank=True, upload_to='men/images/'),
        ),
    ]
