# Generated by Django 3.1 on 2020-09-23 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0008_auto_20200922_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='display',
            name='date',
        ),
    ]
