# Generated by Django 3.1 on 2020-09-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0009_remove_display_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='desc',
            field=models.TextField(max_length=600),
        ),
    ]
